apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain
  namespace: cert-manager
spec:
  dnsNames:
    - "*.doki.life" # 要签发证书的域名，替换成你自己的
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01 # 引用 ClusterIssuer，名字和 letsencrypt-issuer.yaml 中保持一致
  secretName: letsencrypt-tls # 最终签发出来的证书会保存在这个 Secret 里面